# Generated by Django 5.2.4 on 2025-08-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=255)),
                ('detalle', models.CharField(max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Resumen_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255, unique=True)),
                ('facturas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ahorros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
