# Generated by Django 5.2.4 on 2025-08-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_movimiento_cliente_resumen_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='ahorros',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='facturas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resumen_cliente',
            name='ahorros',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resumen_cliente',
            name='facturas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='resumen_cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
