# Generated by Django 5.2.4 on 2025-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0003_alter_resumen_ahorros_alter_resumen_facturas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='movimiento_cliente',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
